import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../config/app_config.dart';
import '../storage/branding_storage.dart';
import 'runtime_theme_service.dart';
import 'theme_cubit.dart';

class RuntimeThemeBootstrapper extends StatefulWidget {
  final Widget child;

  const RuntimeThemeBootstrapper({super.key, required this.child});

  @override
  State<RuntimeThemeBootstrapper> createState() =>
      _RuntimeThemeBootstrapperState();
}

class _RuntimeThemeBootstrapperState extends State<RuntimeThemeBootstrapper> {
  bool _loaded = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();

    if (_loaded) return;
    _loaded = true;

    _loadRuntimeConfig();
  }

  Future<void> _loadRuntimeConfig() async {
    final brandingStorage = BrandingStorage();

    // APP_NAME comes from env directly.
    // Logo native asset is generated by tool/apply_env_branding.ps1.
    await brandingStorage.saveBranding(appName: AppConfig.appName, logoUrl: '');

    final hasEnvTheme =
        AppConfig.themeJsonB64.trim().isNotEmpty ||
        AppConfig.themeJson.trim().isNotEmpty;

    // If theme is coming from env, do not override it with backend runtime config.
    if (hasEnvTheme) {
      return;
    }

    final service = context.read<RuntimeThemeService>();
    final themeCubit = context.read<ThemeCubit>();

    final config = await service.fetchRuntimeConfig();

    if (!mounted || config == null) return;

    if (config.primaryColorHex != null &&
        config.primaryColorHex!.trim().isNotEmpty) {
      await themeCubit.applyThemeFromHex(config.primaryColorHex!);
    }

    await brandingStorage.saveBranding(
      appName: config.appName ?? AppConfig.appName,
      logoUrl: config.logoUrl ?? '',
    );
  }

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}
